### ISSUE TITLE
Baking pan gone after one use...

### ISSUE THREAD

**Issue by kidding82** [frqnny/ChristmasSpirit#10]
In replay of your comment, i post the Issue here. All baking pan's gone after one use. 
We play on Server 1.18.1, if it's important.

Thanks for your commitment 😊

**Comment by frqnny** [comment]
will fix tommorow in a new release

**Comment by kidding82** [comment]
Hey,
with the new update, the issue with the baking pan by crafting ist still there. On our Server, it gone after one use again. I tried the round baking pan and the snowman baking pan.

**Comment by frqnny** [comment]
should explain myself a bit more that idk how to do that. you cant make it its own recipe remainder for some reason so do u just want a piece of iron back at least

**Comment by kidding82** [comment]
I think there is a simple way, if you know. The minecraft-cake is the best example. When you craft it, you get back the empty buckets in the worktable and the item you craft in your hand. But i can't help. I don't know, how to write any modcode ^^...

**Comment by frqnny** [comment]
exactly
