### ISSUE TITLE
[cspirit-1.1.0-1.18.jar] The mod works on singleplayer, but doesn't work on the server.

### ISSUE THREAD

**Issue by adriancpp** [frqnny/ChristmasSpirit#4]
Error while starting the server.

It seems that this is simply the fault of .jar being compiled for release candidate and not for pure release 1.18. I guess because I had the same problem with some of the other mods and uploading the updated version of the mod helped.

I am attaching the log file

[latest.log](https://github.com/frqnny/ChristmasSpirit/files/7642040/latest.log)

**Comment by adriancpp** [comment]
I am hot-headed lol
 so I decided to look for a solution to the problem myself and found it!

All you have to do is in the cspirit.mixins.jsont file change this line
`"compatibilityLevel": "JAVA_17",`
 to:
`"compatibilityLevel": "JAVA_16",`

I compiled the mod locally with that change and now it works on release 1.18 on both client and server!


If everything will be okay at your side, I'm glad I could help :)

**Comment by frqnny** [comment]
not doing that, compatibilityLevel should be java 17 since the game is on java 17. if this is an issue with fabric I'm not going to fix it they will!!!
