### ISSUE TITLE
[cspirit-1.1.3-1.18] Missing translation key for Peppermint seeds & Fully grown Peppermint only drops seeds

### ISSUE THREAD

**Issue by MrRubberDucky** [frqnny/ChristmasSpirit#6]
## Missing Translation Key (en_us) for: item.cspirit.peppermint (Peppermint Seeds)
![the item in question](https://cdn.discordapp.com/attachments/635489949046538270/919004523853389824/2021-12-11_00.15.43.png)

## Fully grown Peppermint from Peppermint seeds seems to only drop seeds:
Picture 1 - Fully Grown Peppermint ![Peppermint](https://cdn.discordapp.com/attachments/635489949046538270/919004522095976458/2021-12-11_00.14.54.png)
Picture 2 - Peppermint being harvested, only drops seeds - tested on multiplayer & singleplayer  ![3 Seeds from a single one, no peppermint](https://cdn.discordapp.com/attachments/635489949046538270/919004522658017330/2021-12-11_00.14.57.png)

**MC version**: 1.18
**Mod Version**: cspirit-1.1.3-1.18
**Fabric Loader version**: 0.12.8
**Mods**: Architectury, Christmas Spirit, Cloth Config v6, Fabric API v0.43.1+1.18, Iris, Iron Chests, Mouse Tweaks, Roughly Enough Items, Sodium, Xaero's Minimap
**Server**: Fabric 1.18
**OS**: Windows 10 x64

**Comment by kidding82** [comment]
Hey,
in 1.2.2 the peppermint-plant still drops only seeds on Server 1.18.1. Singleplayer not testet...  😯
