### ISSUE TITLE
My friends game has an error when he loads minecraft...

### ISSUE THREAD

**Issue by Cookieninja0922** [frqnny/ChristmasSpirit#8]
When my friend launches this mod from the technic launcher it comes up with an error saying something to do with cs sound isnt loading, and I was wondering if it has something to do with the mod? [Modpack Link](https://www.technicpack.net/modpack/dogobweadz-originssmp.1822828)

**Comment by frqnny** [comment]
pls give me the log. idk what is wrong and I'm not going to download the modpack just to look into it. do it rn bc I'm about to release a bugfix update and I'd like to get this one in if it's serious.

**Comment by frqnny** [comment]
no action in this issue so closed
